# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-13 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodblog', '0002_auto_20161114_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth',
            name='email',
            field=models.TextField(default=b'asdf@xyz.com'),
        ),
        migrations.AddField(
            model_name='auth',
            name='password',
            field=models.TextField(default=b'xxxx'),
        ),
        migrations.AddField(
            model_name='auth',
            name='phone',
            field=models.IntegerField(default=b'888888888'),
        ),
    ]
